import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const dungGeunMo = localFont({
  src: "../../public/fonts/DungGeunMo.woff2",
  variable: "--font-dunggeunmo",
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dungGeunMo.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
